version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data